config/routes.rb
Rails.application.routes.draw do
  resources :tweets
  resources :personas
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/persona.rb
class Persona < ApplicationRecord
end

app/models/tweet.rb
class Tweet < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/personas_controller.rb
class PersonasController < ApplicationController
  before_action :set_persona, only: %i[ show edit update destroy ]

  # GET /personas or /personas.json
  def index
    @personas = Persona.all
  end

  # GET /personas/1 or /personas/1.json
  def show
  end

  # GET /personas/new
  def new
    @persona = Persona.new
  end

  # GET /personas/1/edit
  def edit
  end

  # POST /personas or /personas.json
  def create
    @persona = Persona.new(persona_params)

    respond_to do |format|
      if @persona.save
        format.html { redirect_to persona_url(@persona), notice: "Persona was successfully created." }
        format.json { render :show, status: :created, location: @persona }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /personas/1 or /personas/1.json
  def update
    respond_to do |format|
      if @persona.update(persona_params)
        format.html { redirect_to persona_url(@persona), notice: "Persona was successfully updated." }
        format.json { render :show, status: :ok, location: @persona }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @persona.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /personas/1 or /personas/1.json
  def destroy
    @persona.destroy

    respond_to do |format|
      format.html { redirect_to personas_url, notice: "Persona was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_persona
      @persona = Persona.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def persona_params
      params.require(:persona).permit(:nombre, :apellido)
    end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController
  before_action :set_tweet, only: %i[ show edit update destroy ]

  # GET /tweets or /tweets.json
  def index
    @tweets = Tweet.all
  end

  # GET /tweets/1 or /tweets/1.json
  def show
  end

  # GET /tweets/new
  def new
    @tweet = Tweet.new
  end

  # GET /tweets/1/edit
  def edit
  end

  # POST /tweets or /tweets.json
  def create
    @tweet = Tweet.new(tweet_params)

    respond_to do |format|
      if @tweet.save
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully created." }
        format.json { render :show, status: :created, location: @tweet }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tweets/1 or /tweets/1.json
  def update
    respond_to do |format|
      if @tweet.update(tweet_params)
        format.html { redirect_to tweet_url(@tweet), notice: "Tweet was successfully updated." }
        format.json { render :show, status: :ok, location: @tweet }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tweet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tweets/1 or /tweets/1.json
  def destroy
    @tweet.destroy

    respond_to do |format|
      format.html { redirect_to tweets_url, notice: "Tweet was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tweet
      @tweet = Tweet.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tweet_params
      params.require(:tweet).permit(:id, :details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/personas_helper.rb
module PersonasHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/personas/_form.html.erb
<%= form_with(model: persona) do |form| %>
  <% if persona.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(persona.errors.count, "error") %> prohibited this persona from being saved:</h2>

      <ul>
        <% persona.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :apellido, style: "display: block" %>
    <%= form.text_field :apellido %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/personas/_persona.html.erb
<div id="<%= dom_id persona %>">
  <p>
    <strong>Nombre:</strong>
    <%= persona.nombre %>
  </p>

  <p>
    <strong>Apellido:</strong>
    <%= persona.apellido %>
  </p>

</div>

app/views/personas/edit.html.erb
<h1>Editing persona</h1>

<%= render "form", persona: @persona %>

<br>

<div>
  <%= link_to "Show this persona", @persona %> |
  <%= link_to "Back to personas", personas_path %>
</div>

app/views/personas/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Personas</h1>

<div id="personas">
  <% @personas.each do |persona| %>
    <%= render persona %>
    <p>
      <%= link_to "Show this persona", persona %>
    </p>
  <% end %>
</div>

<%= link_to "New persona", new_persona_path %>

app/views/personas/new.html.erb
<h1>New persona</h1>

<%= render "form", persona: @persona %>

<br>

<div>
  <%= link_to "Back to personas", personas_path %>
</div>

app/views/personas/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @persona %>

<div>
  <%= link_to "Edit this persona", edit_persona_path(@persona) %> |
  <%= link_to "Back to personas", personas_path %>

  <%= button_to "Destroy this persona", @persona, method: :delete %>
</div>

app/views/tweets/_form.html.erb
<%= form_with(model: tweet) do |form| %>
  <% if tweet.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(tweet.errors.count, "error") %> prohibited this tweet from being saved:</h2>

      <ul>
        <% tweet.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id, style: "display: block" %>
    <%= form.number_field :id %>
  </div>

  <div>
    <%= form.label :details, style: "display: block" %>
    <%= form.text_field :details %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/tweets/_tweet.html.erb
<div id="<%= dom_id tweet %>">
  <p>
    <strong>Id:</strong>
    <%= tweet.id %>
  </p>

  <p>
    <strong>Details:</strong>
    <%= tweet.details %>
  </p>

</div>

app/views/tweets/edit.html.erb
<h1>Editing tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Show this tweet", @tweet %> |
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Tweets</h1>

<div id="tweets">
  <% @tweets.each do |tweet| %>
    <%= render tweet %>
    <p>
      <%= link_to "Show this tweet", tweet %>
    </p>
  <% end %>
</div>

<%= link_to "New tweet", new_tweet_path %>

app/views/tweets/new.html.erb
<h1>New tweet</h1>

<%= render "form", tweet: @tweet %>

<br>

<div>
  <%= link_to "Back to tweets", tweets_path %>
</div>

app/views/tweets/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @tweet %>

<div>
  <%= link_to "Edit this tweet", edit_tweet_path(@tweet) %> |
  <%= link_to "Back to tweets", tweets_path %>

  <%= button_to "Destroy this tweet", @tweet, method: :delete %>
</div>